apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argoCDManifests/applicationController
  - argoCDManifests/applicationSetController
  - argoCDManifests/argocd
  - argoCDManifests/dexServer
  - argoCDManifests/notificationsController
  - argoCDManifests/redis
  - argoCDManifests/repoServer
  - argoCDManifests/server
