apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applicationController
  - applicationSetController
  - argocd
  - dexServer
  - notificationsController
  - redis
  - repoServer
  - server