apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beszel
  template:
    metadata:
      labels:
        app: beszel
    spec:
      containers:
        - name: beszel
          image: henrygd/beszel:latest
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: beszel-data
              mountPath: /beszel_data
            - name: beszel-socket
              mountPath: /beszel_socket
      volumes:
        - name: beszel-data
          hostPath:
            path: /beszel_data
            type: DirectoryOrCreate
        - name: beszel-socket
          hostPath:
            path: /beszel_socket
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: beszel
spec:
  selector:
    app: beszel
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: LISTEN
              value: "45876"
            - name: HUB_URL
              value: "localhost:8090"
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: beszel-key
                  key: key
          image: henrygd/beszel-agent:latest
          imagePullPolicy: Always
          name: beszel-agent
          ports:
            - containerPort: 45876
              hostPort: 45876
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate